/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AIServiceModelApiResult from './AIServiceModelApiResult';

/**
 * The AIServiceModelApiResultReply model module.
 * @module model/AIServiceModelApiResultReply
 * @version 7.0.0-rc5
 */
class AIServiceModelApiResultReply {
    /**
     * Constructs a new <code>AIServiceModelApiResultReply</code>.
     * @alias module:model/AIServiceModelApiResultReply
     * @param data {Array.<module:model/AIServiceModelApiResult>} 
     * @param totalCount {Number} 
     */
    constructor(data, totalCount) { 
        
        AIServiceModelApiResultReply.initialize(this, data, totalCount);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, data, totalCount) { 
        obj['data'] = data;
        obj['totalCount'] = totalCount;
    }

    /**
     * Constructs a <code>AIServiceModelApiResultReply</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AIServiceModelApiResultReply} obj Optional instance to populate.
     * @return {module:model/AIServiceModelApiResultReply} The populated <code>AIServiceModelApiResultReply</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AIServiceModelApiResultReply();

            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], [AIServiceModelApiResult]);
            }
            if (data.hasOwnProperty('totalCount')) {
                obj['totalCount'] = ApiClient.convertToType(data['totalCount'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AIServiceModelApiResultReply</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AIServiceModelApiResultReply</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AIServiceModelApiResultReply.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['data']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['data'])) {
                throw new Error("Expected the field `data` to be an array in the JSON data but got " + data['data']);
            }
            // validate the optional field `data` (array)
            for (const item of data['data']) {
                AIServiceModelApiResult.validateJSON(item);
            };
        }

        return true;
    }


}

AIServiceModelApiResultReply.RequiredProperties = ["data", "totalCount"];

/**
 * @member {Array.<module:model/AIServiceModelApiResult>} data
 */
AIServiceModelApiResultReply.prototype['data'] = undefined;

/**
 * @member {Number} totalCount
 */
AIServiceModelApiResultReply.prototype['totalCount'] = undefined;






export default AIServiceModelApiResultReply;

