/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AutoTestNamespaceModel model module.
 * @module model/AutoTestNamespaceModel
 * @version 2.0.0
 */
class AutoTestNamespaceModel {
    /**
     * Constructs a new <code>AutoTestNamespaceModel</code>.
     * @alias module:model/AutoTestNamespaceModel
     */
    constructor() { 
        
        AutoTestNamespaceModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AutoTestNamespaceModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AutoTestNamespaceModel} obj Optional instance to populate.
     * @return {module:model/AutoTestNamespaceModel} The populated <code>AutoTestNamespaceModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AutoTestNamespaceModel();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('classes')) {
                obj['classes'] = ApiClient.convertToType(data['classes'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
AutoTestNamespaceModel.prototype['name'] = undefined;

/**
 * @member {Array.<String>} classes
 */
AutoTestNamespaceModel.prototype['classes'] = undefined;






export default AutoTestNamespaceModel;

