/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ExternalFormAllowedValueModel } from './externalFormAllowedValueModel';
import { ExternalFormFieldModel } from './externalFormFieldModel';
import { ExternalFormLinkModel } from './externalFormLinkModel';

export class ExternalFormModel {
    'fields': Array<ExternalFormFieldModel>;
    'possibleValues': { [key: string]: Array<ExternalFormAllowedValueModel>; };
    'links': Array<ExternalFormLinkModel>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "fields",
            "baseName": "fields",
            "type": "Array<ExternalFormFieldModel>"
        },
        {
            "name": "possibleValues",
            "baseName": "possibleValues",
            "type": "{ [key: string]: Array<ExternalFormAllowedValueModel>; }"
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "Array<ExternalFormLinkModel>"
        }    ];

    static getAttributeTypeMap() {
        return ExternalFormModel.attributeTypeMap;
    }
}

