/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ExternalFormAllowedValueModel from './ExternalFormAllowedValueModel';
import ExternalFormFieldModel from './ExternalFormFieldModel';

/**
 * The ExternalFormModel model module.
 * @module model/ExternalFormModel
 * @version 7.2.0
 */
class ExternalFormModel {
    /**
     * Constructs a new <code>ExternalFormModel</code>.
     * @alias module:model/ExternalFormModel
     * @param fields {Array.<module:model/ExternalFormFieldModel>} 
     * @param possibleValues {Object.<String, Array.<module:model/ExternalFormAllowedValueModel>>} 
     */
    constructor(fields, possibleValues) { 
        
        ExternalFormModel.initialize(this, fields, possibleValues);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, fields, possibleValues) { 
        obj['fields'] = fields;
        obj['possibleValues'] = possibleValues;
    }

    /**
     * Constructs a <code>ExternalFormModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ExternalFormModel} obj Optional instance to populate.
     * @return {module:model/ExternalFormModel} The populated <code>ExternalFormModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ExternalFormModel();

            if (data.hasOwnProperty('fields')) {
                obj['fields'] = ApiClient.convertToType(data['fields'], [ExternalFormFieldModel]);
            }
            if (data.hasOwnProperty('possibleValues')) {
                obj['possibleValues'] = ApiClient.convertToType(data['possibleValues'], {'String': [ExternalFormAllowedValueModel]});
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ExternalFormModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ExternalFormModel</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ExternalFormModel.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['fields']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['fields'])) {
                throw new Error("Expected the field `fields` to be an array in the JSON data but got " + data['fields']);
            }
            // validate the optional field `fields` (array)
            for (const item of data['fields']) {
                ExternalFormFieldModel.validateJSON(item);
            };
        }

        return true;
    }


}

ExternalFormModel.RequiredProperties = ["fields", "possibleValues"];

/**
 * @member {Array.<module:model/ExternalFormFieldModel>} fields
 */
ExternalFormModel.prototype['fields'] = undefined;

/**
 * @member {Object.<String, Array.<module:model/ExternalFormAllowedValueModel>>} possibleValues
 */
ExternalFormModel.prototype['possibleValues'] = undefined;






export default ExternalFormModel;

