/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GlobalSearchRequest model module.
 * @module model/GlobalSearchRequest
 * @version 7.0.0-rc2
 */
class GlobalSearchRequest {
    /**
     * Constructs a new <code>GlobalSearchRequest</code>.
     * @alias module:model/GlobalSearchRequest
     * @param query {String} 
     * @param take {Number} 
     * @param skip {Number} 
     */
    constructor(query, take, skip) { 
        
        GlobalSearchRequest.initialize(this, query, take, skip);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, query, take, skip) { 
        obj['query'] = query;
        obj['take'] = take;
        obj['skip'] = skip;
    }

    /**
     * Constructs a <code>GlobalSearchRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GlobalSearchRequest} obj Optional instance to populate.
     * @return {module:model/GlobalSearchRequest} The populated <code>GlobalSearchRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GlobalSearchRequest();

            if (data.hasOwnProperty('query')) {
                obj['query'] = ApiClient.convertToType(data['query'], 'String');
            }
            if (data.hasOwnProperty('resourceType')) {
                obj['resourceType'] = ApiClient.convertToType(data['resourceType'], 'String');
            }
            if (data.hasOwnProperty('take')) {
                obj['take'] = ApiClient.convertToType(data['take'], 'Number');
            }
            if (data.hasOwnProperty('skip')) {
                obj['skip'] = ApiClient.convertToType(data['skip'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GlobalSearchRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GlobalSearchRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of GlobalSearchRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['query'] && !(typeof data['query'] === 'string' || data['query'] instanceof String)) {
            throw new Error("Expected the field `query` to be a primitive type in the JSON string but got " + data['query']);
        }
        // ensure the json data is a string
        if (data['resourceType'] && !(typeof data['resourceType'] === 'string' || data['resourceType'] instanceof String)) {
            throw new Error("Expected the field `resourceType` to be a primitive type in the JSON string but got " + data['resourceType']);
        }

        return true;
    }


}

GlobalSearchRequest.RequiredProperties = ["query", "take", "skip"];

/**
 * @member {String} query
 */
GlobalSearchRequest.prototype['query'] = undefined;

/**
 * @member {String} resourceType
 */
GlobalSearchRequest.prototype['resourceType'] = undefined;

/**
 * @member {Number} take
 */
GlobalSearchRequest.prototype['take'] = undefined;

/**
 * @member {Number} skip
 */
GlobalSearchRequest.prototype['skip'] = undefined;






export default GlobalSearchRequest;

