/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class GuidExtractionModel {
    'include'?: Set<string> | null;
    'exclude'?: Set<string> | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "include",
            "baseName": "include",
            "type": "Set<string>"
        },
        {
            "name": "exclude",
            "baseName": "exclude",
            "type": "Set<string>"
        }    ];

    static getAttributeTypeMap() {
        return GuidExtractionModel.attributeTypeMap;
    }
}

