/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CompositeFilter from './CompositeFilter';
import Group from './Group';
import Mode from './Mode';
import Order from './Order';
import Page from './Page';

/**
 * The Inquiry model module.
 * @module model/Inquiry
 * @version 7.2.7
 */
class Inquiry {
    /**
     * Constructs a new <code>Inquiry</code>.
     * @alias module:model/Inquiry
     * @param order {Array.<module:model/Order>} 
     * @param mode {module:model/Mode} 
     */
    constructor(order, mode) { 
        
        Inquiry.initialize(this, order, mode);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, order, mode) { 
        obj['order'] = order;
        obj['mode'] = mode;
    }

    /**
     * Constructs a <code>Inquiry</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Inquiry} obj Optional instance to populate.
     * @return {module:model/Inquiry} The populated <code>Inquiry</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Inquiry();

            if (data.hasOwnProperty('group')) {
                obj['group'] = ApiClient.convertToType(data['group'], Group);
            }
            if (data.hasOwnProperty('filter')) {
                obj['filter'] = ApiClient.convertToType(data['filter'], CompositeFilter);
            }
            if (data.hasOwnProperty('order')) {
                obj['order'] = ApiClient.convertToType(data['order'], [Order]);
            }
            if (data.hasOwnProperty('page')) {
                obj['page'] = ApiClient.convertToType(data['page'], Page);
            }
            if (data.hasOwnProperty('mode')) {
                obj['mode'] = ApiClient.convertToType(data['mode'], Mode);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Inquiry</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Inquiry</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Inquiry.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `group`
        if (data['group']) { // data not null
          Group.validateJSON(data['group']);
        }
        // validate the optional field `filter`
        if (data['filter']) { // data not null
          CompositeFilter.validateJSON(data['filter']);
        }
        if (data['order']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['order'])) {
                throw new Error("Expected the field `order` to be an array in the JSON data but got " + data['order']);
            }
            // validate the optional field `order` (array)
            for (const item of data['order']) {
                Order.validateJSON(item);
            };
        }
        // validate the optional field `page`
        if (data['page']) { // data not null
          Page.validateJSON(data['page']);
        }

        return true;
    }


}

Inquiry.RequiredProperties = ["order", "mode"];

/**
 * @member {module:model/Group} group
 */
Inquiry.prototype['group'] = undefined;

/**
 * @member {module:model/CompositeFilter} filter
 */
Inquiry.prototype['filter'] = undefined;

/**
 * @member {Array.<module:model/Order>} order
 */
Inquiry.prototype['order'] = undefined;

/**
 * @member {module:model/Page} page
 */
Inquiry.prototype['page'] = undefined;

/**
 * @member {module:model/Mode} mode
 */
Inquiry.prototype['mode'] = undefined;






export default Inquiry;

