/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ParameterPutModel model module.
 * @module model/ParameterPutModel
 * @version 2.0.0
 */
class ParameterPutModel {
    /**
     * Constructs a new <code>ParameterPutModel</code>.
     * @alias module:model/ParameterPutModel
     * @param value {String} 
     * @param name {String} 
     */
    constructor(value, name) { 
        
        ParameterPutModel.initialize(this, value, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, value, name) { 
        obj['value'] = value;
        obj['name'] = name;
    }

    /**
     * Constructs a <code>ParameterPutModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ParameterPutModel} obj Optional instance to populate.
     * @return {module:model/ParameterPutModel} The populated <code>ParameterPutModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ParameterPutModel();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
ParameterPutModel.prototype['id'] = undefined;

/**
 * @member {String} value
 */
ParameterPutModel.prototype['value'] = undefined;

/**
 * @member {String} name
 */
ParameterPutModel.prototype['name'] = undefined;






export default ParameterPutModel;

