/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { FailureCategory } from './failureCategory';
import { FailureClassRegexApiResult } from './failureClassRegexApiResult';

export class ProjectDetailedFailureCategoryApiResult {
    /**
    * Failure category identifier
    */
    'id': string;
    /**
    * Failure category name
    */
    'name'?: string | null;
    /**
    * Indicates if the entity is deleted
    */
    'isDeleted': boolean;
    /**
    * Category type
    */
    'failureCategory': FailureCategory;
    /**
    * Failure category creation date
    */
    'createdDate': Date;
    /**
    * Failure category creator identifier
    */
    'createdById': string;
    /**
    * Failure category last modification date
    */
    'modifiedDate'?: Date | null;
    /**
    * Failure category last modifier identifier
    */
    'modifiedById'?: string | null;
    /**
    * Failure category regexes
    */
    'failureClassRegexes': Array<FailureClassRegexApiResult>;
    /**
    * Projects relations count
    */
    'projectsCount': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "isDeleted",
            "baseName": "isDeleted",
            "type": "boolean"
        },
        {
            "name": "failureCategory",
            "baseName": "failureCategory",
            "type": "FailureCategory"
        },
        {
            "name": "createdDate",
            "baseName": "createdDate",
            "type": "Date"
        },
        {
            "name": "createdById",
            "baseName": "createdById",
            "type": "string"
        },
        {
            "name": "modifiedDate",
            "baseName": "modifiedDate",
            "type": "Date"
        },
        {
            "name": "modifiedById",
            "baseName": "modifiedById",
            "type": "string"
        },
        {
            "name": "failureClassRegexes",
            "baseName": "failureClassRegexes",
            "type": "Array<FailureClassRegexApiResult>"
        },
        {
            "name": "projectsCount",
            "baseName": "projectsCount",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return ProjectDetailedFailureCategoryApiResult.attributeTypeMap;
    }
}

export namespace ProjectDetailedFailureCategoryApiResult {
}
