/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CustomAttributeModel } from './customAttributeModel';

export class ProjectCustomAttributeTemplateGetModel {
    /**
    * Unique ID of the custom attributes template
    */
    'id'?: string;
    /**
    * Indicates if the custom attribute template is deleted
    */
    'isDeleted'?: boolean;
    /**
    * Name of the custom attribute template
    */
    'name'?: string | null;
    /**
    * Attributes of the template
    */
    'customAttributeModels'?: Array<CustomAttributeModel> | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "isDeleted",
            "baseName": "isDeleted",
            "type": "boolean"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "customAttributeModels",
            "baseName": "customAttributeModels",
            "type": "Array<CustomAttributeModel>"
        }    ];

    static getAttributeTypeMap() {
        return ProjectCustomAttributeTemplateGetModel.attributeTypeMap;
    }
}

