/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TagsExtractionApiModel from './TagsExtractionApiModel';
import TagsFilterApiModel from './TagsFilterApiModel';

/**
 * The SelectTagsApiModel model module.
 * @module model/SelectTagsApiModel
 * @version 7.2.0
 */
class SelectTagsApiModel {
    /**
     * Constructs a new <code>SelectTagsApiModel</code>.
     * @alias module:model/SelectTagsApiModel
     */
    constructor() { 
        
        SelectTagsApiModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SelectTagsApiModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SelectTagsApiModel} obj Optional instance to populate.
     * @return {module:model/SelectTagsApiModel} The populated <code>SelectTagsApiModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SelectTagsApiModel();

            if (data.hasOwnProperty('filter')) {
                obj['filter'] = ApiClient.convertToType(data['filter'], TagsFilterApiModel);
            }
            if (data.hasOwnProperty('extractionModel')) {
                obj['extractionModel'] = ApiClient.convertToType(data['extractionModel'], TagsExtractionApiModel);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SelectTagsApiModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SelectTagsApiModel</code>.
     */
    static validateJSON(data) {
        // validate the optional field `filter`
        if (data['filter']) { // data not null
          TagsFilterApiModel.validateJSON(data['filter']);
        }
        // validate the optional field `extractionModel`
        if (data['extractionModel']) { // data not null
          TagsExtractionApiModel.validateJSON(data['extractionModel']);
        }

        return true;
    }


}



/**
 * Filters to select tags
 * @member {module:model/TagsFilterApiModel} filter
 */
SelectTagsApiModel.prototype['filter'] = undefined;

/**
 * Filters to extract tags
 * @member {module:model/TagsExtractionApiModel} extractionModel
 */
SelectTagsApiModel.prototype['extractionModel'] = undefined;






export default SelectTagsApiModel;

