/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { TagShortModel } from './tagShortModel';
import { TestPlanStatusModel } from './testPlanStatusModel';
import { TestPointAnalyticResult } from './testPointAnalyticResult';

export class TestPlanWithAnalyticModel {
    'analytic'?: TestPointAnalyticResult;
    'status': TestPlanStatusModel;
    /**
    * Set when test plan is starter (status changed to: In Progress)
    */
    'startedOn'?: Date | null;
    /**
    * set when test plan status is completed (status changed to: Completed)
    */
    'completedOn'?: Date | null;
    'createdDate'?: Date | null;
    'modifiedDate'?: Date | null;
    'createdById'?: string;
    'modifiedById'?: string | null;
    /**
    * Used for search Test plan
    */
    'globalId'?: number;
    'isDeleted'?: boolean;
    'lockedDate'?: Date | null;
    'id': string;
    'lockedById'?: string | null;
    'tags'?: Array<TagShortModel> | null;
    'name': string;
    /**
    * Used for analytics
    */
    'startDate'?: Date | null;
    /**
    * Used for analytics
    */
    'endDate'?: Date | null;
    'description'?: string | null;
    'build'?: string | null;
    'projectId': string;
    'productName'?: string | null;
    'hasAutomaticDurationTimer'?: boolean | null;
    'attributes'?: { [key: string]: any; } | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "analytic",
            "baseName": "analytic",
            "type": "TestPointAnalyticResult"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "TestPlanStatusModel"
        },
        {
            "name": "startedOn",
            "baseName": "startedOn",
            "type": "Date"
        },
        {
            "name": "completedOn",
            "baseName": "completedOn",
            "type": "Date"
        },
        {
            "name": "createdDate",
            "baseName": "createdDate",
            "type": "Date"
        },
        {
            "name": "modifiedDate",
            "baseName": "modifiedDate",
            "type": "Date"
        },
        {
            "name": "createdById",
            "baseName": "createdById",
            "type": "string"
        },
        {
            "name": "modifiedById",
            "baseName": "modifiedById",
            "type": "string"
        },
        {
            "name": "globalId",
            "baseName": "globalId",
            "type": "number"
        },
        {
            "name": "isDeleted",
            "baseName": "isDeleted",
            "type": "boolean"
        },
        {
            "name": "lockedDate",
            "baseName": "lockedDate",
            "type": "Date"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "lockedById",
            "baseName": "lockedById",
            "type": "string"
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "Array<TagShortModel>"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "startDate",
            "baseName": "startDate",
            "type": "Date"
        },
        {
            "name": "endDate",
            "baseName": "endDate",
            "type": "Date"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "build",
            "baseName": "build",
            "type": "string"
        },
        {
            "name": "projectId",
            "baseName": "projectId",
            "type": "string"
        },
        {
            "name": "productName",
            "baseName": "productName",
            "type": "string"
        },
        {
            "name": "hasAutomaticDurationTimer",
            "baseName": "hasAutomaticDurationTimer",
            "type": "boolean"
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "{ [key: string]: any; }"
        }    ];

    static getAttributeTypeMap() {
        return TestPlanWithAnalyticModel.attributeTypeMap;
    }
}

