/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TestSuiteV2PutModel model module.
 * @module model/TestSuiteV2PutModel
 * @version 7.0.0
 */
class TestSuiteV2PutModel {
    /**
     * Constructs a new <code>TestSuiteV2PutModel</code>.
     * @alias module:model/TestSuiteV2PutModel
     * @param id {String} 
     * @param name {String} 
     * @param isDeleted {Boolean} 
     */
    constructor(id, name, isDeleted) { 
        
        TestSuiteV2PutModel.initialize(this, id, name, isDeleted);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, name, isDeleted) { 
        obj['id'] = id;
        obj['name'] = name;
        obj['isDeleted'] = isDeleted;
    }

    /**
     * Constructs a <code>TestSuiteV2PutModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TestSuiteV2PutModel} obj Optional instance to populate.
     * @return {module:model/TestSuiteV2PutModel} The populated <code>TestSuiteV2PutModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TestSuiteV2PutModel();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('parentId')) {
                obj['parentId'] = ApiClient.convertToType(data['parentId'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('isDeleted')) {
                obj['isDeleted'] = ApiClient.convertToType(data['isDeleted'], 'Boolean');
            }
            if (data.hasOwnProperty('autoRefresh')) {
                obj['autoRefresh'] = ApiClient.convertToType(data['autoRefresh'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TestSuiteV2PutModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TestSuiteV2PutModel</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of TestSuiteV2PutModel.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['parentId'] && !(typeof data['parentId'] === 'string' || data['parentId'] instanceof String)) {
            throw new Error("Expected the field `parentId` to be a primitive type in the JSON string but got " + data['parentId']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }

        return true;
    }


}

TestSuiteV2PutModel.RequiredProperties = ["id", "name", "isDeleted"];

/**
 * @member {String} id
 */
TestSuiteV2PutModel.prototype['id'] = undefined;

/**
 * @member {String} parentId
 */
TestSuiteV2PutModel.prototype['parentId'] = undefined;

/**
 * @member {String} name
 */
TestSuiteV2PutModel.prototype['name'] = undefined;

/**
 * @member {Boolean} isDeleted
 */
TestSuiteV2PutModel.prototype['isDeleted'] = undefined;

/**
 * @member {Boolean} autoRefresh
 */
TestSuiteV2PutModel.prototype['autoRefresh'] = undefined;






export default TestSuiteV2PutModel;

