/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AuditApiResult from './AuditApiResult';
import ConfigurationShortApiResult from './ConfigurationShortApiResult';
import LastTestResultApiResult from './LastTestResultApiResult';
import ParameterShortApiResult from './ParameterShortApiResult';
import TestPlanTestPointsTestSuiteSearchApiResult from './TestPlanTestPointsTestSuiteSearchApiResult';
import TestPlanTestPointsWorkItemSearchApiResult from './TestPlanTestPointsWorkItemSearchApiResult';
import TestStatusShortApiResult from './TestStatusShortApiResult';
import UserNameApiResult from './UserNameApiResult';

/**
 * The TestPlanTestPointsSearchApiResult model module.
 * @module model/TestPlanTestPointsSearchApiResult
 * @version 7.0.0
 */
class TestPlanTestPointsSearchApiResult {
    /**
     * Constructs a new <code>TestPlanTestPointsSearchApiResult</code>.
     * @alias module:model/TestPlanTestPointsSearchApiResult
     * @param id {String} 
     * @param created {module:model/AuditApiResult} 
     * @param status {String} 
     * @param statusModel {module:model/TestStatusShortApiResult} 
     * @param inProgress {Boolean} 
     * @param configuration {module:model/ConfigurationShortApiResult} 
     * @param testSuite {module:model/TestPlanTestPointsTestSuiteSearchApiResult} 
     * @param workItem {module:model/TestPlanTestPointsWorkItemSearchApiResult} 
     * @param parameters {Array.<module:model/ParameterShortApiResult>} 
     */
    constructor(id, created, status, statusModel, inProgress, configuration, testSuite, workItem, parameters) { 
        
        TestPlanTestPointsSearchApiResult.initialize(this, id, created, status, statusModel, inProgress, configuration, testSuite, workItem, parameters);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, created, status, statusModel, inProgress, configuration, testSuite, workItem, parameters) { 
        obj['id'] = id;
        obj['created'] = created;
        obj['status'] = status;
        obj['statusModel'] = statusModel;
        obj['inProgress'] = inProgress;
        obj['configuration'] = configuration;
        obj['testSuite'] = testSuite;
        obj['workItem'] = workItem;
        obj['parameters'] = parameters;
    }

    /**
     * Constructs a <code>TestPlanTestPointsSearchApiResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TestPlanTestPointsSearchApiResult} obj Optional instance to populate.
     * @return {module:model/TestPlanTestPointsSearchApiResult} The populated <code>TestPlanTestPointsSearchApiResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TestPlanTestPointsSearchApiResult();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('created')) {
                obj['created'] = ApiClient.convertToType(data['created'], AuditApiResult);
            }
            if (data.hasOwnProperty('modified')) {
                obj['modified'] = ApiClient.convertToType(data['modified'], AuditApiResult);
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('statusModel')) {
                obj['statusModel'] = ApiClient.convertToType(data['statusModel'], TestStatusShortApiResult);
            }
            if (data.hasOwnProperty('inProgress')) {
                obj['inProgress'] = ApiClient.convertToType(data['inProgress'], 'Boolean');
            }
            if (data.hasOwnProperty('configuration')) {
                obj['configuration'] = ApiClient.convertToType(data['configuration'], ConfigurationShortApiResult);
            }
            if (data.hasOwnProperty('tester')) {
                obj['tester'] = ApiClient.convertToType(data['tester'], UserNameApiResult);
            }
            if (data.hasOwnProperty('testSuite')) {
                obj['testSuite'] = ApiClient.convertToType(data['testSuite'], TestPlanTestPointsTestSuiteSearchApiResult);
            }
            if (data.hasOwnProperty('workItem')) {
                obj['workItem'] = ApiClient.convertToType(data['workItem'], TestPlanTestPointsWorkItemSearchApiResult);
            }
            if (data.hasOwnProperty('parameters')) {
                obj['parameters'] = ApiClient.convertToType(data['parameters'], [ParameterShortApiResult]);
            }
            if (data.hasOwnProperty('lastTestResult')) {
                obj['lastTestResult'] = ApiClient.convertToType(data['lastTestResult'], LastTestResultApiResult);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TestPlanTestPointsSearchApiResult</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TestPlanTestPointsSearchApiResult</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of TestPlanTestPointsSearchApiResult.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // validate the optional field `created`
        if (data['created']) { // data not null
          AuditApiResult.validateJSON(data['created']);
        }
        // validate the optional field `modified`
        if (data['modified']) { // data not null
          AuditApiResult.validateJSON(data['modified']);
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }
        // validate the optional field `statusModel`
        if (data['statusModel']) { // data not null
          TestStatusShortApiResult.validateJSON(data['statusModel']);
        }
        // validate the optional field `configuration`
        if (data['configuration']) { // data not null
          ConfigurationShortApiResult.validateJSON(data['configuration']);
        }
        // validate the optional field `tester`
        if (data['tester']) { // data not null
          UserNameApiResult.validateJSON(data['tester']);
        }
        // validate the optional field `testSuite`
        if (data['testSuite']) { // data not null
          TestPlanTestPointsTestSuiteSearchApiResult.validateJSON(data['testSuite']);
        }
        // validate the optional field `workItem`
        if (data['workItem']) { // data not null
          TestPlanTestPointsWorkItemSearchApiResult.validateJSON(data['workItem']);
        }
        if (data['parameters']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['parameters'])) {
                throw new Error("Expected the field `parameters` to be an array in the JSON data but got " + data['parameters']);
            }
            // validate the optional field `parameters` (array)
            for (const item of data['parameters']) {
                ParameterShortApiResult.validateJSON(item);
            };
        }
        // validate the optional field `lastTestResult`
        if (data['lastTestResult']) { // data not null
          LastTestResultApiResult.validateJSON(data['lastTestResult']);
        }

        return true;
    }


}

TestPlanTestPointsSearchApiResult.RequiredProperties = ["id", "created", "status", "statusModel", "inProgress", "configuration", "testSuite", "workItem", "parameters"];

/**
 * @member {String} id
 */
TestPlanTestPointsSearchApiResult.prototype['id'] = undefined;

/**
 * @member {module:model/AuditApiResult} created
 */
TestPlanTestPointsSearchApiResult.prototype['created'] = undefined;

/**
 * @member {module:model/AuditApiResult} modified
 */
TestPlanTestPointsSearchApiResult.prototype['modified'] = undefined;

/**
 * @member {String} status
 */
TestPlanTestPointsSearchApiResult.prototype['status'] = undefined;

/**
 * @member {module:model/TestStatusShortApiResult} statusModel
 */
TestPlanTestPointsSearchApiResult.prototype['statusModel'] = undefined;

/**
 * @member {Boolean} inProgress
 */
TestPlanTestPointsSearchApiResult.prototype['inProgress'] = undefined;

/**
 * @member {module:model/ConfigurationShortApiResult} configuration
 */
TestPlanTestPointsSearchApiResult.prototype['configuration'] = undefined;

/**
 * @member {module:model/UserNameApiResult} tester
 */
TestPlanTestPointsSearchApiResult.prototype['tester'] = undefined;

/**
 * @member {module:model/TestPlanTestPointsTestSuiteSearchApiResult} testSuite
 */
TestPlanTestPointsSearchApiResult.prototype['testSuite'] = undefined;

/**
 * @member {module:model/TestPlanTestPointsWorkItemSearchApiResult} workItem
 */
TestPlanTestPointsSearchApiResult.prototype['workItem'] = undefined;

/**
 * @member {Array.<module:model/ParameterShortApiResult>} parameters
 */
TestPlanTestPointsSearchApiResult.prototype['parameters'] = undefined;

/**
 * @member {module:model/LastTestResultApiResult} lastTestResult
 */
TestPlanTestPointsSearchApiResult.prototype['lastTestResult'] = undefined;






export default TestPlanTestPointsSearchApiResult;

