/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GuidExtractionModel from './GuidExtractionModel';

/**
 * The TestPlanTestPointsExtractionApiModel model module.
 * @module model/TestPlanTestPointsExtractionApiModel
 * @version 7.0.0-rc5
 */
class TestPlanTestPointsExtractionApiModel {
    /**
     * Constructs a new <code>TestPlanTestPointsExtractionApiModel</code>.
     * @alias module:model/TestPlanTestPointsExtractionApiModel
     */
    constructor() { 
        
        TestPlanTestPointsExtractionApiModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TestPlanTestPointsExtractionApiModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TestPlanTestPointsExtractionApiModel} obj Optional instance to populate.
     * @return {module:model/TestPlanTestPointsExtractionApiModel} The populated <code>TestPlanTestPointsExtractionApiModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TestPlanTestPointsExtractionApiModel();

            if (data.hasOwnProperty('ids')) {
                obj['ids'] = ApiClient.convertToType(data['ids'], GuidExtractionModel);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TestPlanTestPointsExtractionApiModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TestPlanTestPointsExtractionApiModel</code>.
     */
    static validateJSON(data) {
        // validate the optional field `ids`
        if (data['ids']) { // data not null
          GuidExtractionModel.validateJSON(data['ids']);
        }

        return true;
    }


}



/**
 * Extraction parameters for test points
 * @member {module:model/GuidExtractionModel} ids
 */
TestPlanTestPointsExtractionApiModel.prototype['ids'] = undefined;






export default TestPlanTestPointsExtractionApiModel;

