/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AttachmentApiResult from './AttachmentApiResult';
import AutoTestApiResult from './AutoTestApiResult';
import AutoTestStepResultsApiResult from './AutoTestStepResultsApiResult';
import LinkApiResult from './LinkApiResult';
import StepCommentApiModel from './StepCommentApiModel';
import TestPointShortApiResult from './TestPointShortApiResult';
import TestResultFailureClassApiResult from './TestResultFailureClassApiResult';
import TestStatusApiResult from './TestStatusApiResult';

/**
 * The TestResultApiResult model module.
 * @module model/TestResultApiResult
 * @version 7.2.0
 */
class TestResultApiResult {
    /**
     * Constructs a new <code>TestResultApiResult</code>.
     * @alias module:model/TestResultApiResult
     * @param id {String} 
     * @param outcome {String} 
     * @param testRunId {String} 
     * @param configurationId {String} 
     * @param status {module:model/TestStatusApiResult} 
     * @param attachments {Array.<module:model/AttachmentApiResult>} 
     * @param links {Array.<module:model/LinkApiResult>} 
     * @param failureClasses {Array.<module:model/TestResultFailureClassApiResult>} 
     * @param createdDate {Date} 
     * @param createdById {String} 
     * @param isDeleted {Boolean} 
     */
    constructor(id, outcome, testRunId, configurationId, status, attachments, links, failureClasses, createdDate, createdById, isDeleted) { 
        
        TestResultApiResult.initialize(this, id, outcome, testRunId, configurationId, status, attachments, links, failureClasses, createdDate, createdById, isDeleted);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, outcome, testRunId, configurationId, status, attachments, links, failureClasses, createdDate, createdById, isDeleted) { 
        obj['id'] = id;
        obj['outcome'] = outcome;
        obj['testRunId'] = testRunId;
        obj['configurationId'] = configurationId;
        obj['status'] = status;
        obj['attachments'] = attachments;
        obj['links'] = links;
        obj['failureClasses'] = failureClasses;
        obj['createdDate'] = createdDate;
        obj['createdById'] = createdById;
        obj['isDeleted'] = isDeleted;
    }

    /**
     * Constructs a <code>TestResultApiResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TestResultApiResult} obj Optional instance to populate.
     * @return {module:model/TestResultApiResult} The populated <code>TestResultApiResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TestResultApiResult();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('startedOn')) {
                obj['startedOn'] = ApiClient.convertToType(data['startedOn'], 'Date');
            }
            if (data.hasOwnProperty('completedOn')) {
                obj['completedOn'] = ApiClient.convertToType(data['completedOn'], 'Date');
            }
            if (data.hasOwnProperty('durationInMs')) {
                obj['durationInMs'] = ApiClient.convertToType(data['durationInMs'], 'Number');
            }
            if (data.hasOwnProperty('traces')) {
                obj['traces'] = ApiClient.convertToType(data['traces'], 'String');
            }
            if (data.hasOwnProperty('failureType')) {
                obj['failureType'] = ApiClient.convertToType(data['failureType'], 'String');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('runByUserId')) {
                obj['runByUserId'] = ApiClient.convertToType(data['runByUserId'], 'String');
            }
            if (data.hasOwnProperty('stoppedByUserId')) {
                obj['stoppedByUserId'] = ApiClient.convertToType(data['stoppedByUserId'], 'String');
            }
            if (data.hasOwnProperty('outcome')) {
                obj['outcome'] = ApiClient.convertToType(data['outcome'], 'String');
            }
            if (data.hasOwnProperty('autoTestId')) {
                obj['autoTestId'] = ApiClient.convertToType(data['autoTestId'], 'String');
            }
            if (data.hasOwnProperty('testPointId')) {
                obj['testPointId'] = ApiClient.convertToType(data['testPointId'], 'String');
            }
            if (data.hasOwnProperty('testRunId')) {
                obj['testRunId'] = ApiClient.convertToType(data['testRunId'], 'String');
            }
            if (data.hasOwnProperty('configurationId')) {
                obj['configurationId'] = ApiClient.convertToType(data['configurationId'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], TestStatusApiResult);
            }
            if (data.hasOwnProperty('testPoint')) {
                obj['testPoint'] = ApiClient.convertToType(data['testPoint'], TestPointShortApiResult);
            }
            if (data.hasOwnProperty('autoTest')) {
                obj['autoTest'] = ApiClient.convertToType(data['autoTest'], AutoTestApiResult);
            }
            if (data.hasOwnProperty('autoTestStepResults')) {
                obj['autoTestStepResults'] = ApiClient.convertToType(data['autoTestStepResults'], [AutoTestStepResultsApiResult]);
            }
            if (data.hasOwnProperty('setupResults')) {
                obj['setupResults'] = ApiClient.convertToType(data['setupResults'], [AutoTestStepResultsApiResult]);
            }
            if (data.hasOwnProperty('teardownResults')) {
                obj['teardownResults'] = ApiClient.convertToType(data['teardownResults'], [AutoTestStepResultsApiResult]);
            }
            if (data.hasOwnProperty('workItemVersionId')) {
                obj['workItemVersionId'] = ApiClient.convertToType(data['workItemVersionId'], 'String');
            }
            if (data.hasOwnProperty('workItemVersionNumber')) {
                obj['workItemVersionNumber'] = ApiClient.convertToType(data['workItemVersionNumber'], 'Number');
            }
            if (data.hasOwnProperty('attachments')) {
                obj['attachments'] = ApiClient.convertToType(data['attachments'], [AttachmentApiResult]);
            }
            if (data.hasOwnProperty('links')) {
                obj['links'] = ApiClient.convertToType(data['links'], [LinkApiResult]);
            }
            if (data.hasOwnProperty('failureClasses')) {
                obj['failureClasses'] = ApiClient.convertToType(data['failureClasses'], [TestResultFailureClassApiResult]);
            }
            if (data.hasOwnProperty('stepComments')) {
                obj['stepComments'] = ApiClient.convertToType(data['stepComments'], [StepCommentApiModel]);
            }
            if (data.hasOwnProperty('parameters')) {
                obj['parameters'] = ApiClient.convertToType(data['parameters'], {'String': 'String'});
            }
            if (data.hasOwnProperty('properties')) {
                obj['properties'] = ApiClient.convertToType(data['properties'], {'String': 'String'});
            }
            if (data.hasOwnProperty('createdDate')) {
                obj['createdDate'] = ApiClient.convertToType(data['createdDate'], 'Date');
            }
            if (data.hasOwnProperty('modifiedDate')) {
                obj['modifiedDate'] = ApiClient.convertToType(data['modifiedDate'], 'Date');
            }
            if (data.hasOwnProperty('createdById')) {
                obj['createdById'] = ApiClient.convertToType(data['createdById'], 'String');
            }
            if (data.hasOwnProperty('modifiedById')) {
                obj['modifiedById'] = ApiClient.convertToType(data['modifiedById'], 'String');
            }
            if (data.hasOwnProperty('isDeleted')) {
                obj['isDeleted'] = ApiClient.convertToType(data['isDeleted'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TestResultApiResult</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TestResultApiResult</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of TestResultApiResult.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['traces'] && !(typeof data['traces'] === 'string' || data['traces'] instanceof String)) {
            throw new Error("Expected the field `traces` to be a primitive type in the JSON string but got " + data['traces']);
        }
        // ensure the json data is a string
        if (data['failureType'] && !(typeof data['failureType'] === 'string' || data['failureType'] instanceof String)) {
            throw new Error("Expected the field `failureType` to be a primitive type in the JSON string but got " + data['failureType']);
        }
        // ensure the json data is a string
        if (data['message'] && !(typeof data['message'] === 'string' || data['message'] instanceof String)) {
            throw new Error("Expected the field `message` to be a primitive type in the JSON string but got " + data['message']);
        }
        // ensure the json data is a string
        if (data['runByUserId'] && !(typeof data['runByUserId'] === 'string' || data['runByUserId'] instanceof String)) {
            throw new Error("Expected the field `runByUserId` to be a primitive type in the JSON string but got " + data['runByUserId']);
        }
        // ensure the json data is a string
        if (data['stoppedByUserId'] && !(typeof data['stoppedByUserId'] === 'string' || data['stoppedByUserId'] instanceof String)) {
            throw new Error("Expected the field `stoppedByUserId` to be a primitive type in the JSON string but got " + data['stoppedByUserId']);
        }
        // ensure the json data is a string
        if (data['outcome'] && !(typeof data['outcome'] === 'string' || data['outcome'] instanceof String)) {
            throw new Error("Expected the field `outcome` to be a primitive type in the JSON string but got " + data['outcome']);
        }
        // ensure the json data is a string
        if (data['autoTestId'] && !(typeof data['autoTestId'] === 'string' || data['autoTestId'] instanceof String)) {
            throw new Error("Expected the field `autoTestId` to be a primitive type in the JSON string but got " + data['autoTestId']);
        }
        // ensure the json data is a string
        if (data['testPointId'] && !(typeof data['testPointId'] === 'string' || data['testPointId'] instanceof String)) {
            throw new Error("Expected the field `testPointId` to be a primitive type in the JSON string but got " + data['testPointId']);
        }
        // ensure the json data is a string
        if (data['testRunId'] && !(typeof data['testRunId'] === 'string' || data['testRunId'] instanceof String)) {
            throw new Error("Expected the field `testRunId` to be a primitive type in the JSON string but got " + data['testRunId']);
        }
        // ensure the json data is a string
        if (data['configurationId'] && !(typeof data['configurationId'] === 'string' || data['configurationId'] instanceof String)) {
            throw new Error("Expected the field `configurationId` to be a primitive type in the JSON string but got " + data['configurationId']);
        }
        // validate the optional field `status`
        if (data['status']) { // data not null
          TestStatusApiResult.validateJSON(data['status']);
        }
        // validate the optional field `testPoint`
        if (data['testPoint']) { // data not null
          TestPointShortApiResult.validateJSON(data['testPoint']);
        }
        // validate the optional field `autoTest`
        if (data['autoTest']) { // data not null
          AutoTestApiResult.validateJSON(data['autoTest']);
        }
        if (data['autoTestStepResults']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['autoTestStepResults'])) {
                throw new Error("Expected the field `autoTestStepResults` to be an array in the JSON data but got " + data['autoTestStepResults']);
            }
            // validate the optional field `autoTestStepResults` (array)
            for (const item of data['autoTestStepResults']) {
                AutoTestStepResultsApiResult.validateJSON(item);
            };
        }
        if (data['setupResults']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['setupResults'])) {
                throw new Error("Expected the field `setupResults` to be an array in the JSON data but got " + data['setupResults']);
            }
            // validate the optional field `setupResults` (array)
            for (const item of data['setupResults']) {
                AutoTestStepResultsApiResult.validateJSON(item);
            };
        }
        if (data['teardownResults']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['teardownResults'])) {
                throw new Error("Expected the field `teardownResults` to be an array in the JSON data but got " + data['teardownResults']);
            }
            // validate the optional field `teardownResults` (array)
            for (const item of data['teardownResults']) {
                AutoTestStepResultsApiResult.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['workItemVersionId'] && !(typeof data['workItemVersionId'] === 'string' || data['workItemVersionId'] instanceof String)) {
            throw new Error("Expected the field `workItemVersionId` to be a primitive type in the JSON string but got " + data['workItemVersionId']);
        }
        if (data['attachments']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['attachments'])) {
                throw new Error("Expected the field `attachments` to be an array in the JSON data but got " + data['attachments']);
            }
            // validate the optional field `attachments` (array)
            for (const item of data['attachments']) {
                AttachmentApiResult.validateJSON(item);
            };
        }
        if (data['links']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['links'])) {
                throw new Error("Expected the field `links` to be an array in the JSON data but got " + data['links']);
            }
            // validate the optional field `links` (array)
            for (const item of data['links']) {
                LinkApiResult.validateJSON(item);
            };
        }
        if (data['failureClasses']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['failureClasses'])) {
                throw new Error("Expected the field `failureClasses` to be an array in the JSON data but got " + data['failureClasses']);
            }
            // validate the optional field `failureClasses` (array)
            for (const item of data['failureClasses']) {
                TestResultFailureClassApiResult.validateJSON(item);
            };
        }
        if (data['stepComments']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['stepComments'])) {
                throw new Error("Expected the field `stepComments` to be an array in the JSON data but got " + data['stepComments']);
            }
            // validate the optional field `stepComments` (array)
            for (const item of data['stepComments']) {
                StepCommentApiModel.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['createdById'] && !(typeof data['createdById'] === 'string' || data['createdById'] instanceof String)) {
            throw new Error("Expected the field `createdById` to be a primitive type in the JSON string but got " + data['createdById']);
        }
        // ensure the json data is a string
        if (data['modifiedById'] && !(typeof data['modifiedById'] === 'string' || data['modifiedById'] instanceof String)) {
            throw new Error("Expected the field `modifiedById` to be a primitive type in the JSON string but got " + data['modifiedById']);
        }

        return true;
    }


}

TestResultApiResult.RequiredProperties = ["id", "outcome", "testRunId", "configurationId", "status", "attachments", "links", "failureClasses", "createdDate", "createdById", "isDeleted"];

/**
 * @member {String} id
 */
TestResultApiResult.prototype['id'] = undefined;

/**
 * @member {Date} startedOn
 */
TestResultApiResult.prototype['startedOn'] = undefined;

/**
 * @member {Date} completedOn
 */
TestResultApiResult.prototype['completedOn'] = undefined;

/**
 * @member {Number} durationInMs
 */
TestResultApiResult.prototype['durationInMs'] = undefined;

/**
 * @member {String} traces
 */
TestResultApiResult.prototype['traces'] = undefined;

/**
 * @member {String} failureType
 */
TestResultApiResult.prototype['failureType'] = undefined;

/**
 * @member {String} message
 */
TestResultApiResult.prototype['message'] = undefined;

/**
 * @member {String} runByUserId
 */
TestResultApiResult.prototype['runByUserId'] = undefined;

/**
 * @member {String} stoppedByUserId
 */
TestResultApiResult.prototype['stoppedByUserId'] = undefined;

/**
 * @member {String} outcome
 */
TestResultApiResult.prototype['outcome'] = undefined;

/**
 * @member {String} autoTestId
 */
TestResultApiResult.prototype['autoTestId'] = undefined;

/**
 * @member {String} testPointId
 */
TestResultApiResult.prototype['testPointId'] = undefined;

/**
 * @member {String} testRunId
 */
TestResultApiResult.prototype['testRunId'] = undefined;

/**
 * @member {String} configurationId
 */
TestResultApiResult.prototype['configurationId'] = undefined;

/**
 * @member {module:model/TestStatusApiResult} status
 */
TestResultApiResult.prototype['status'] = undefined;

/**
 * @member {module:model/TestPointShortApiResult} testPoint
 */
TestResultApiResult.prototype['testPoint'] = undefined;

/**
 * @member {module:model/AutoTestApiResult} autoTest
 */
TestResultApiResult.prototype['autoTest'] = undefined;

/**
 * @member {Array.<module:model/AutoTestStepResultsApiResult>} autoTestStepResults
 */
TestResultApiResult.prototype['autoTestStepResults'] = undefined;

/**
 * @member {Array.<module:model/AutoTestStepResultsApiResult>} setupResults
 */
TestResultApiResult.prototype['setupResults'] = undefined;

/**
 * @member {Array.<module:model/AutoTestStepResultsApiResult>} teardownResults
 */
TestResultApiResult.prototype['teardownResults'] = undefined;

/**
 * @member {String} workItemVersionId
 */
TestResultApiResult.prototype['workItemVersionId'] = undefined;

/**
 * @member {Number} workItemVersionNumber
 */
TestResultApiResult.prototype['workItemVersionNumber'] = undefined;

/**
 * @member {Array.<module:model/AttachmentApiResult>} attachments
 */
TestResultApiResult.prototype['attachments'] = undefined;

/**
 * @member {Array.<module:model/LinkApiResult>} links
 */
TestResultApiResult.prototype['links'] = undefined;

/**
 * @member {Array.<module:model/TestResultFailureClassApiResult>} failureClasses
 */
TestResultApiResult.prototype['failureClasses'] = undefined;

/**
 * @member {Array.<module:model/StepCommentApiModel>} stepComments
 */
TestResultApiResult.prototype['stepComments'] = undefined;

/**
 * @member {Object.<String, String>} parameters
 */
TestResultApiResult.prototype['parameters'] = undefined;

/**
 * @member {Object.<String, String>} properties
 */
TestResultApiResult.prototype['properties'] = undefined;

/**
 * @member {Date} createdDate
 */
TestResultApiResult.prototype['createdDate'] = undefined;

/**
 * @member {Date} modifiedDate
 */
TestResultApiResult.prototype['modifiedDate'] = undefined;

/**
 * @member {String} createdById
 */
TestResultApiResult.prototype['createdById'] = undefined;

/**
 * @member {String} modifiedById
 */
TestResultApiResult.prototype['modifiedById'] = undefined;

/**
 * @member {Boolean} isDeleted
 */
TestResultApiResult.prototype['isDeleted'] = undefined;






export default TestResultApiResult;

