/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ProjectTestPlansFilterModel } from './projectTestPlansFilterModel';
import { TestPlanExtractionModel } from './testPlanExtractionModel';

export class TestPlanSelectModel {
    'filter'?: ProjectTestPlansFilterModel | null;
    'extractionModel'?: TestPlanExtractionModel | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "filter",
            "baseName": "filter",
            "type": "ProjectTestPlansFilterModel"
        },
        {
            "name": "extractionModel",
            "baseName": "extractionModel",
            "type": "TestPlanExtractionModel"
        }    ];

    static getAttributeTypeMap() {
        return TestPlanSelectModel.attributeTypeMap;
    }
}

