/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { TestResultsStatisticsFailureCategoriesApiResult } from './testResultsStatisticsFailureCategoriesApiResult';
import { TestResultsStatisticsStatusesApiResult } from './testResultsStatisticsStatusesApiResult';

export class TestResultsStatisticsApiResult {
    /**
    * Test results counts aggregated by outcome
    */
    'statuses': TestResultsStatisticsStatusesApiResult;
    /**
    * Test results counts aggregated by result failure categories
    */
    'failureCategories': TestResultsStatisticsFailureCategoriesApiResult;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "statuses",
            "baseName": "statuses",
            "type": "TestResultsStatisticsStatusesApiResult"
        },
        {
            "name": "failureCategories",
            "baseName": "failureCategories",
            "type": "TestResultsStatisticsFailureCategoriesApiResult"
        }    ];

    static getAttributeTypeMap() {
        return TestResultsStatisticsApiResult.attributeTypeMap;
    }
}

