/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AttachmentApiResult } from './attachmentApiResult';
import { AutoTestResultReasonShort } from './autoTestResultReasonShort';
import { LinkShort } from './linkShort';
import { TestStatusApiResult } from './testStatusApiResult';

export class TestResultShortResponse {
    /**
    * Unique ID of the test result
    */
    'id': string;
    /**
    * Name of autotest represented by the test result
    */
    'name': string;
    /**
    * Global ID of autotest represented by the test result
    */
    'autotestGlobalId': number;
    /**
    * Unique ID of test run where the test result is located
    */
    'testRunId': string;
    /**
    * Unique ID of configuration which the test result uses
    */
    'configurationId': string;
    /**
    * Name of configuration which the test result uses
    */
    'configurationName': string;
    /**
    * Outcome of the test result
    *
    * @deprecated
    */
    'outcome'?: string | null;
    'status'?: TestStatusApiResult | null;
    /**
    * Collection of result reasons which the test result have
    */
    'resultReasons': Array<AutoTestResultReasonShort>;
    /**
    * Comment to the test result
    */
    'comment'?: string | null;
    /**
    * Date when the test result was completed or started or created
    *
    * @deprecated
    */
    'date': Date;
    /**
    * Date when the test result has been created
    */
    'createdDate': Date;
    /**
    * Date when the test result has been modified
    */
    'modifiedDate'?: Date | null;
    /**
    * Date when the test result has been started
    */
    'startedOn'?: Date | null;
    /**
    * Date when the test result has been completed
    */
    'completedOn'?: Date | null;
    /**
    * Time which it took to run the test
    */
    'duration'?: number | null;
    /**
    * Collection of links attached to the test result
    */
    'links': Array<LinkShort>;
    /**
    * Collection of files attached to the test result
    */
    'attachments': Array<AttachmentApiResult>;
    /**
    * Run count
    */
    'rerunCompletedCount': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "autotestGlobalId",
            "baseName": "autotestGlobalId",
            "type": "number"
        },
        {
            "name": "testRunId",
            "baseName": "testRunId",
            "type": "string"
        },
        {
            "name": "configurationId",
            "baseName": "configurationId",
            "type": "string"
        },
        {
            "name": "configurationName",
            "baseName": "configurationName",
            "type": "string"
        },
        {
            "name": "outcome",
            "baseName": "outcome",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "TestStatusApiResult"
        },
        {
            "name": "resultReasons",
            "baseName": "resultReasons",
            "type": "Array<AutoTestResultReasonShort>"
        },
        {
            "name": "comment",
            "baseName": "comment",
            "type": "string"
        },
        {
            "name": "date",
            "baseName": "date",
            "type": "Date"
        },
        {
            "name": "createdDate",
            "baseName": "createdDate",
            "type": "Date"
        },
        {
            "name": "modifiedDate",
            "baseName": "modifiedDate",
            "type": "Date"
        },
        {
            "name": "startedOn",
            "baseName": "startedOn",
            "type": "Date"
        },
        {
            "name": "completedOn",
            "baseName": "completedOn",
            "type": "Date"
        },
        {
            "name": "duration",
            "baseName": "duration",
            "type": "number"
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "Array<LinkShort>"
        },
        {
            "name": "attachments",
            "baseName": "attachments",
            "type": "Array<AttachmentApiResult>"
        },
        {
            "name": "rerunCompletedCount",
            "baseName": "rerunCompletedCount",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return TestResultShortResponse.attributeTypeMap;
    }
}

