/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TestPlanGroupByTestSuite model module.
 * @module model/TestPlanGroupByTestSuite
 * @version 7.0.0-rc2
 */
class TestPlanGroupByTestSuite {
    /**
     * Constructs a new <code>TestPlanGroupByTestSuite</code>.
     * @alias module:model/TestPlanGroupByTestSuite
     * @param testSuiteId {String} 
     * @param testSuiteName {String} 
     * @param value {Number} 
     */
    constructor(testSuiteId, testSuiteName, value) { 
        
        TestPlanGroupByTestSuite.initialize(this, testSuiteId, testSuiteName, value);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, testSuiteId, testSuiteName, value) { 
        obj['testSuiteId'] = testSuiteId;
        obj['testSuiteName'] = testSuiteName;
        obj['value'] = value;
    }

    /**
     * Constructs a <code>TestPlanGroupByTestSuite</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TestPlanGroupByTestSuite} obj Optional instance to populate.
     * @return {module:model/TestPlanGroupByTestSuite} The populated <code>TestPlanGroupByTestSuite</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TestPlanGroupByTestSuite();

            if (data.hasOwnProperty('testSuiteId')) {
                obj['testSuiteId'] = ApiClient.convertToType(data['testSuiteId'], 'String');
            }
            if (data.hasOwnProperty('testSuiteName')) {
                obj['testSuiteName'] = ApiClient.convertToType(data['testSuiteName'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TestPlanGroupByTestSuite</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TestPlanGroupByTestSuite</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of TestPlanGroupByTestSuite.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['testSuiteId'] && !(typeof data['testSuiteId'] === 'string' || data['testSuiteId'] instanceof String)) {
            throw new Error("Expected the field `testSuiteId` to be a primitive type in the JSON string but got " + data['testSuiteId']);
        }
        // ensure the json data is a string
        if (data['testSuiteName'] && !(typeof data['testSuiteName'] === 'string' || data['testSuiteName'] instanceof String)) {
            throw new Error("Expected the field `testSuiteName` to be a primitive type in the JSON string but got " + data['testSuiteName']);
        }

        return true;
    }


}

TestPlanGroupByTestSuite.RequiredProperties = ["testSuiteId", "testSuiteName", "value"];

/**
 * @member {String} testSuiteId
 */
TestPlanGroupByTestSuite.prototype['testSuiteId'] = undefined;

/**
 * @member {String} testSuiteName
 */
TestPlanGroupByTestSuite.prototype['testSuiteName'] = undefined;

/**
 * @member {Number} value
 */
TestPlanGroupByTestSuite.prototype['value'] = undefined;






export default TestPlanGroupByTestSuite;

