/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ShortConfiguration from './ShortConfiguration';

/**
 * The TestSuiteChangeViewModel model module.
 * @module model/TestSuiteChangeViewModel
 * @version 7.0.0-rc2
 */
class TestSuiteChangeViewModel {
    /**
     * Constructs a new <code>TestSuiteChangeViewModel</code>.
     * @alias module:model/TestSuiteChangeViewModel
     * @param id {String} 
     * @param name {String} 
     * @param workItemCount {Number} 
     */
    constructor(id, name, workItemCount) { 
        
        TestSuiteChangeViewModel.initialize(this, id, name, workItemCount);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, name, workItemCount) { 
        obj['id'] = id;
        obj['name'] = name;
        obj['workItemCount'] = workItemCount;
    }

    /**
     * Constructs a <code>TestSuiteChangeViewModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TestSuiteChangeViewModel} obj Optional instance to populate.
     * @return {module:model/TestSuiteChangeViewModel} The populated <code>TestSuiteChangeViewModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TestSuiteChangeViewModel();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('configurations')) {
                obj['configurations'] = ApiClient.convertToType(data['configurations'], [ShortConfiguration]);
            }
            if (data.hasOwnProperty('workItemCount')) {
                obj['workItemCount'] = ApiClient.convertToType(data['workItemCount'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TestSuiteChangeViewModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TestSuiteChangeViewModel</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of TestSuiteChangeViewModel.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        if (data['configurations']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['configurations'])) {
                throw new Error("Expected the field `configurations` to be an array in the JSON data but got " + data['configurations']);
            }
            // validate the optional field `configurations` (array)
            for (const item of data['configurations']) {
                ShortConfiguration.validateJSON(item);
            };
        }

        return true;
    }


}

TestSuiteChangeViewModel.RequiredProperties = ["id", "name", "workItemCount"];

/**
 * @member {String} id
 */
TestSuiteChangeViewModel.prototype['id'] = undefined;

/**
 * @member {String} name
 */
TestSuiteChangeViewModel.prototype['name'] = undefined;

/**
 * @member {Array.<module:model/ShortConfiguration>} configurations
 */
TestSuiteChangeViewModel.prototype['configurations'] = undefined;

/**
 * @member {Number} workItemCount
 */
TestSuiteChangeViewModel.prototype['workItemCount'] = undefined;






export default TestSuiteChangeViewModel;

