/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class TestSuiteTypeApiResult.
* @enum {}
* @readonly
*/
export default class TestSuiteTypeApiResult {
    
        /**
         * value: "Custom"
         * @const
         */
        "Custom" = "Custom";

    
        /**
         * value: "Dynamic"
         * @const
         */
        "Dynamic" = "Dynamic";

    
        /**
         * value: "Tree"
         * @const
         */
        "Tree" = "Tree";

    

    /**
    * Returns a <code>TestSuiteTypeApiResult</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/TestSuiteTypeApiResult} The enum <code>TestSuiteTypeApiResult</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

