/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AttachmentPutModelAutoTestStepResultsModel } from './attachmentPutModelAutoTestStepResultsModel';
import { AttachmentUpdateRequest } from './attachmentUpdateRequest';
import { Link } from './link';
import { StepResultApiModel } from './stepResultApiModel';
import { TestResultOutcome } from './testResultOutcome';
import { TestResultStepCommentUpdateRequest } from './testResultStepCommentUpdateRequest';

export class TestResultUpdateV2Request {
    'failureClassIds'?: Array<string> | null;
    /**
    * @deprecated
    */
    'outcome'?: TestResultOutcome | null;
    'statusCode'?: string | null;
    'comment'?: string | null;
    'links'?: Array<Link> | null;
    'stepResults'?: Array<StepResultApiModel> | null;
    'attachments'?: Array<AttachmentUpdateRequest> | null;
    /**
    * @deprecated
    */
    'durationInMs'?: number | null;
    'duration'?: number | null;
    'stepComments'?: Array<TestResultStepCommentUpdateRequest> | null;
    'setupResults'?: Array<AttachmentPutModelAutoTestStepResultsModel> | null;
    'teardownResults'?: Array<AttachmentPutModelAutoTestStepResultsModel> | null;
    'message'?: string | null;
    'trace'?: string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "failureClassIds",
            "baseName": "failureClassIds",
            "type": "Array<string>"
        },
        {
            "name": "outcome",
            "baseName": "outcome",
            "type": "TestResultOutcome"
        },
        {
            "name": "statusCode",
            "baseName": "statusCode",
            "type": "string"
        },
        {
            "name": "comment",
            "baseName": "comment",
            "type": "string"
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "Array<Link>"
        },
        {
            "name": "stepResults",
            "baseName": "stepResults",
            "type": "Array<StepResultApiModel>"
        },
        {
            "name": "attachments",
            "baseName": "attachments",
            "type": "Array<AttachmentUpdateRequest>"
        },
        {
            "name": "durationInMs",
            "baseName": "durationInMs",
            "type": "number"
        },
        {
            "name": "duration",
            "baseName": "duration",
            "type": "number"
        },
        {
            "name": "stepComments",
            "baseName": "stepComments",
            "type": "Array<TestResultStepCommentUpdateRequest>"
        },
        {
            "name": "setupResults",
            "baseName": "setupResults",
            "type": "Array<AttachmentPutModelAutoTestStepResultsModel>"
        },
        {
            "name": "teardownResults",
            "baseName": "teardownResults",
            "type": "Array<AttachmentPutModelAutoTestStepResultsModel>"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "trace",
            "baseName": "trace",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return TestResultUpdateV2Request.attributeTypeMap;
    }
}

export namespace TestResultUpdateV2Request {
}
