/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SharedStepChangeViewModel from './SharedStepChangeViewModel';

/**
 * The WorkItemStepChangeViewModel model module.
 * @module model/WorkItemStepChangeViewModel
 * @version 2.0.0
 */
class WorkItemStepChangeViewModel {
    /**
     * Constructs a new <code>WorkItemStepChangeViewModel</code>.
     * @alias module:model/WorkItemStepChangeViewModel
     */
    constructor() { 
        
        WorkItemStepChangeViewModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>WorkItemStepChangeViewModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WorkItemStepChangeViewModel} obj Optional instance to populate.
     * @return {module:model/WorkItemStepChangeViewModel} The populated <code>WorkItemStepChangeViewModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WorkItemStepChangeViewModel();

            if (data.hasOwnProperty('action')) {
                obj['action'] = ApiClient.convertToType(data['action'], 'String');
            }
            if (data.hasOwnProperty('expected')) {
                obj['expected'] = ApiClient.convertToType(data['expected'], 'String');
            }
            if (data.hasOwnProperty('comments')) {
                obj['comments'] = ApiClient.convertToType(data['comments'], 'String');
            }
            if (data.hasOwnProperty('testData')) {
                obj['testData'] = ApiClient.convertToType(data['testData'], 'String');
            }
            if (data.hasOwnProperty('index')) {
                obj['index'] = ApiClient.convertToType(data['index'], 'Number');
            }
            if (data.hasOwnProperty('workItemId')) {
                obj['workItemId'] = ApiClient.convertToType(data['workItemId'], 'String');
            }
            if (data.hasOwnProperty('workItem')) {
                obj['workItem'] = SharedStepChangeViewModel.constructFromObject(data['workItem']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} action
 */
WorkItemStepChangeViewModel.prototype['action'] = undefined;

/**
 * @member {String} expected
 */
WorkItemStepChangeViewModel.prototype['expected'] = undefined;

/**
 * @member {String} comments
 */
WorkItemStepChangeViewModel.prototype['comments'] = undefined;

/**
 * @member {String} testData
 */
WorkItemStepChangeViewModel.prototype['testData'] = undefined;

/**
 * @member {Number} index
 */
WorkItemStepChangeViewModel.prototype['index'] = undefined;

/**
 * @member {String} workItemId
 */
WorkItemStepChangeViewModel.prototype['workItemId'] = undefined;

/**
 * @member {module:model/SharedStepChangeViewModel} workItem
 */
WorkItemStepChangeViewModel.prototype['workItem'] = undefined;






export default WorkItemStepChangeViewModel;

