/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The WorkflowStatusApiModel model module.
 * @module model/WorkflowStatusApiModel
 * @version 7.2.0
 */
class WorkflowStatusApiModel {
    /**
     * Constructs a new <code>WorkflowStatusApiModel</code>.
     * @alias module:model/WorkflowStatusApiModel
     * @param statusId {String} 
     * @param priority {Number} 
     */
    constructor(statusId, priority) { 
        
        WorkflowStatusApiModel.initialize(this, statusId, priority);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, statusId, priority) { 
        obj['statusId'] = statusId;
        obj['priority'] = priority;
    }

    /**
     * Constructs a <code>WorkflowStatusApiModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WorkflowStatusApiModel} obj Optional instance to populate.
     * @return {module:model/WorkflowStatusApiModel} The populated <code>WorkflowStatusApiModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WorkflowStatusApiModel();

            if (data.hasOwnProperty('statusId')) {
                obj['statusId'] = ApiClient.convertToType(data['statusId'], 'String');
            }
            if (data.hasOwnProperty('priority')) {
                obj['priority'] = ApiClient.convertToType(data['priority'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>WorkflowStatusApiModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>WorkflowStatusApiModel</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of WorkflowStatusApiModel.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['statusId'] && !(typeof data['statusId'] === 'string' || data['statusId'] instanceof String)) {
            throw new Error("Expected the field `statusId` to be a primitive type in the JSON string but got " + data['statusId']);
        }

        return true;
    }


}

WorkflowStatusApiModel.RequiredProperties = ["statusId", "priority"];

/**
 * @member {String} statusId
 */
WorkflowStatusApiModel.prototype['statusId'] = undefined;

/**
 * @member {Number} priority
 */
WorkflowStatusApiModel.prototype['priority'] = undefined;






export default WorkflowStatusApiModel;

