/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import WorkItemLinkChangeViewModel from './WorkItemLinkChangeViewModel';

/**
 * The WorkItemLinkChangeViewModelArrayWorkItemChangedFieldViewModel model module.
 * @module model/WorkItemLinkChangeViewModelArrayWorkItemChangedFieldViewModel
 * @version 2.0.0
 */
class WorkItemLinkChangeViewModelArrayWorkItemChangedFieldViewModel {
    /**
     * Constructs a new <code>WorkItemLinkChangeViewModelArrayWorkItemChangedFieldViewModel</code>.
     * @alias module:model/WorkItemLinkChangeViewModelArrayWorkItemChangedFieldViewModel
     */
    constructor() { 
        
        WorkItemLinkChangeViewModelArrayWorkItemChangedFieldViewModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>WorkItemLinkChangeViewModelArrayWorkItemChangedFieldViewModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WorkItemLinkChangeViewModelArrayWorkItemChangedFieldViewModel} obj Optional instance to populate.
     * @return {module:model/WorkItemLinkChangeViewModelArrayWorkItemChangedFieldViewModel} The populated <code>WorkItemLinkChangeViewModelArrayWorkItemChangedFieldViewModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WorkItemLinkChangeViewModelArrayWorkItemChangedFieldViewModel();

            if (data.hasOwnProperty('oldValue')) {
                obj['oldValue'] = ApiClient.convertToType(data['oldValue'], [WorkItemLinkChangeViewModel]);
            }
            if (data.hasOwnProperty('newValue')) {
                obj['newValue'] = ApiClient.convertToType(data['newValue'], [WorkItemLinkChangeViewModel]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/WorkItemLinkChangeViewModel>} oldValue
 */
WorkItemLinkChangeViewModelArrayWorkItemChangedFieldViewModel.prototype['oldValue'] = undefined;

/**
 * @member {Array.<module:model/WorkItemLinkChangeViewModel>} newValue
 */
WorkItemLinkChangeViewModelArrayWorkItemChangedFieldViewModel.prototype['newValue'] = undefined;






export default WorkItemLinkChangeViewModelArrayWorkItemChangedFieldViewModel;

