/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import WorkItemLinkExtractionApiModel from './WorkItemLinkExtractionApiModel';
import WorkItemLinkUrlFilterApiModel from './WorkItemLinkUrlFilterApiModel';

/**
 * The WorkItemLinkUrlApiModel model module.
 * @module model/WorkItemLinkUrlApiModel
 * @version 7.0.0-rc1
 */
class WorkItemLinkUrlApiModel {
    /**
     * Constructs a new <code>WorkItemLinkUrlApiModel</code>.
     * @alias module:model/WorkItemLinkUrlApiModel
     * @param filter {module:model/WorkItemLinkUrlFilterApiModel} 
     * @param extractionModel {module:model/WorkItemLinkExtractionApiModel} 
     */
    constructor(filter, extractionModel) { 
        
        WorkItemLinkUrlApiModel.initialize(this, filter, extractionModel);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, filter, extractionModel) { 
        obj['filter'] = filter;
        obj['extractionModel'] = extractionModel;
    }

    /**
     * Constructs a <code>WorkItemLinkUrlApiModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WorkItemLinkUrlApiModel} obj Optional instance to populate.
     * @return {module:model/WorkItemLinkUrlApiModel} The populated <code>WorkItemLinkUrlApiModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WorkItemLinkUrlApiModel();

            if (data.hasOwnProperty('filter')) {
                obj['filter'] = ApiClient.convertToType(data['filter'], WorkItemLinkUrlFilterApiModel);
            }
            if (data.hasOwnProperty('extractionModel')) {
                obj['extractionModel'] = ApiClient.convertToType(data['extractionModel'], WorkItemLinkExtractionApiModel);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>WorkItemLinkUrlApiModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>WorkItemLinkUrlApiModel</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of WorkItemLinkUrlApiModel.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `filter`
        if (data['filter']) { // data not null
          WorkItemLinkUrlFilterApiModel.validateJSON(data['filter']);
        }
        // validate the optional field `extractionModel`
        if (data['extractionModel']) { // data not null
          WorkItemLinkExtractionApiModel.validateJSON(data['extractionModel']);
        }

        return true;
    }


}

WorkItemLinkUrlApiModel.RequiredProperties = ["filter", "extractionModel"];

/**
 * @member {module:model/WorkItemLinkUrlFilterApiModel} filter
 */
WorkItemLinkUrlApiModel.prototype['filter'] = undefined;

/**
 * @member {module:model/WorkItemLinkExtractionApiModel} extractionModel
 */
WorkItemLinkUrlApiModel.prototype['extractionModel'] = undefined;






export default WorkItemLinkUrlApiModel;

