/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The WorkItemLikeModel model module.
 * @module model/WorkItemLikeModel
 * @version 2.0.0
 */
class WorkItemLikeModel {
    /**
     * Constructs a new <code>WorkItemLikeModel</code>.
     * @alias module:model/WorkItemLikeModel
     */
    constructor() { 
        
        WorkItemLikeModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>WorkItemLikeModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WorkItemLikeModel} obj Optional instance to populate.
     * @return {module:model/WorkItemLikeModel} The populated <code>WorkItemLikeModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WorkItemLikeModel();

            if (data.hasOwnProperty('workItemId')) {
                obj['workItemId'] = ApiClient.convertToType(data['workItemId'], 'String');
            }
            if (data.hasOwnProperty('createdDate')) {
                obj['createdDate'] = ApiClient.convertToType(data['createdDate'], 'Date');
            }
            if (data.hasOwnProperty('modifiedDate')) {
                obj['modifiedDate'] = ApiClient.convertToType(data['modifiedDate'], 'Date');
            }
            if (data.hasOwnProperty('createdById')) {
                obj['createdById'] = ApiClient.convertToType(data['createdById'], 'String');
            }
            if (data.hasOwnProperty('modifiedById')) {
                obj['modifiedById'] = ApiClient.convertToType(data['modifiedById'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('isDeleted')) {
                obj['isDeleted'] = ApiClient.convertToType(data['isDeleted'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {String} workItemId
 */
WorkItemLikeModel.prototype['workItemId'] = undefined;

/**
 * @member {Date} createdDate
 */
WorkItemLikeModel.prototype['createdDate'] = undefined;

/**
 * @member {Date} modifiedDate
 */
WorkItemLikeModel.prototype['modifiedDate'] = undefined;

/**
 * @member {String} createdById
 */
WorkItemLikeModel.prototype['createdById'] = undefined;

/**
 * @member {String} modifiedById
 */
WorkItemLikeModel.prototype['modifiedById'] = undefined;

/**
 * @member {String} id
 */
WorkItemLikeModel.prototype['id'] = undefined;

/**
 * @member {Boolean} isDeleted
 */
WorkItemLikeModel.prototype['isDeleted'] = undefined;






export default WorkItemLikeModel;

