/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class WorkItemChangedAttributeViewModel {
    'type'?: string | null;
    'oldAttributeName'?: string | null;
    'newAttributeName'?: string | null;
    'oldValue'?: any | null;
    'newValue'?: any | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "oldAttributeName",
            "baseName": "oldAttributeName",
            "type": "string"
        },
        {
            "name": "newAttributeName",
            "baseName": "newAttributeName",
            "type": "string"
        },
        {
            "name": "oldValue",
            "baseName": "oldValue",
            "type": "any"
        },
        {
            "name": "newValue",
            "baseName": "newValue",
            "type": "any"
        }    ];

    static getAttributeTypeMap() {
        return WorkItemChangedAttributeViewModel.attributeTypeMap;
    }
}

