/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import TestPointSelectModel from '../model/TestPointSelectModel';
import TestPointShortGetModel from '../model/TestPointShortGetModel';
import TestRunModel from '../model/TestRunModel';
import WorkItemModel from '../model/WorkItemModel';

/**
* TestPoints service.
* @module api/TestPointsApi
* @version 2.0.0
*/
export default class TestPointsApi {

    /**
    * Constructs a new TestPointsApi. 
    * @alias module:api/TestPointsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the apiV2TestPointsIdTestRunsGet operation.
     * @callback module:api/TestPointsApi~apiV2TestPointsIdTestRunsGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/TestRunModel>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} id 
     * @param {module:api/TestPointsApi~apiV2TestPointsIdTestRunsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/TestRunModel>}
     */
    apiV2TestPointsIdTestRunsGet(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling apiV2TestPointsIdTestRunsGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer or PrivateToken'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [TestRunModel];
      return this.apiClient.callApi(
        '/api/v2/testPoints/{id}/testRuns', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the apiV2TestPointsIdWorkItemGet operation.
     * @callback module:api/TestPointsApi~apiV2TestPointsIdWorkItemGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/WorkItemModel} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} id 
     * @param {module:api/TestPointsApi~apiV2TestPointsIdWorkItemGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/WorkItemModel}
     */
    apiV2TestPointsIdWorkItemGet(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling apiV2TestPointsIdWorkItemGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer or PrivateToken'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = WorkItemModel;
      return this.apiClient.callApi(
        '/api/v2/testPoints/{id}/workItem', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the apiV2TestPointsSearchPost operation.
     * @callback module:api/TestPointsApi~apiV2TestPointsSearchPostCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/TestPointShortGetModel>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Object} opts Optional parameters
     * @param {Number} opts.skip Amount of items to be skipped (offset)
     * @param {Number} opts.take Amount of items to be taken (limit)
     * @param {String} opts.orderBy SQL-like  ORDER BY statement (column1 ASC|DESC , column2 ASC|DESC)
     * @param {String} opts.searchField Property name for searching
     * @param {String} opts.searchValue Value for searching
     * @param {module:model/TestPointSelectModel} opts.testPointSelectModel 
     * @param {module:api/TestPointsApi~apiV2TestPointsSearchPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/TestPointShortGetModel>}
     */
    apiV2TestPointsSearchPost(opts, callback) {
      opts = opts || {};
      let postBody = opts['testPointSelectModel'];

      let pathParams = {
      };
      let queryParams = {
        'Skip': opts['skip'],
        'Take': opts['take'],
        'OrderBy': opts['orderBy'],
        'SearchField': opts['searchField'],
        'SearchValue': opts['searchValue']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer or PrivateToken'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = [TestPointShortGetModel];
      return this.apiClient.callApi(
        '/api/v2/testPoints/search', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
