/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TestitApiClient);
  }
}(this, function(expect, TestitApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TestitApiClient.CustomAttributeSearchResponseModel();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CustomAttributeSearchResponseModel', function() {
    it('should create an instance of CustomAttributeSearchResponseModel', function() {
      // uncomment below and update the code to test CustomAttributeSearchResponseModel
      //var instance = new TestitApiClient.CustomAttributeSearchResponseModel();
      //expect(instance).to.be.a(TestitApiClient.CustomAttributeSearchResponseModel);
    });

    it('should have the property workItemUsage (base name: "workItemUsage")', function() {
      // uncomment below and update the code to test the property workItemUsage
      //var instance = new TestitApiClient.CustomAttributeSearchResponseModel();
      //expect(instance).to.be();
    });

    it('should have the property testPlanUsage (base name: "testPlanUsage")', function() {
      // uncomment below and update the code to test the property testPlanUsage
      //var instance = new TestitApiClient.CustomAttributeSearchResponseModel();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new TestitApiClient.CustomAttributeSearchResponseModel();
      //expect(instance).to.be();
    });

    it('should have the property options (base name: "options")', function() {
      // uncomment below and update the code to test the property options
      //var instance = new TestitApiClient.CustomAttributeSearchResponseModel();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new TestitApiClient.CustomAttributeSearchResponseModel();
      //expect(instance).to.be();
    });

    it('should have the property isDeleted (base name: "isDeleted")', function() {
      // uncomment below and update the code to test the property isDeleted
      //var instance = new TestitApiClient.CustomAttributeSearchResponseModel();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new TestitApiClient.CustomAttributeSearchResponseModel();
      //expect(instance).to.be();
    });

    it('should have the property isEnabled (base name: "isEnabled")', function() {
      // uncomment below and update the code to test the property isEnabled
      //var instance = new TestitApiClient.CustomAttributeSearchResponseModel();
      //expect(instance).to.be();
    });

    it('should have the property isRequired (base name: "isRequired")', function() {
      // uncomment below and update the code to test the property isRequired
      //var instance = new TestitApiClient.CustomAttributeSearchResponseModel();
      //expect(instance).to.be();
    });

    it('should have the property isGlobal (base name: "isGlobal")', function() {
      // uncomment below and update the code to test the property isGlobal
      //var instance = new TestitApiClient.CustomAttributeSearchResponseModel();
      //expect(instance).to.be();
    });

  });

}));
