/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TestitApiClient);
  }
}(this, function(expect, TestitApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TestitApiClient.GetShortProjectsApiModel();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('GetShortProjectsApiModel', function() {
    it('should create an instance of GetShortProjectsApiModel', function() {
      // uncomment below and update the code to test GetShortProjectsApiModel
      //var instance = new TestitApiClient.GetShortProjectsApiModel();
      //expect(instance).to.be.a(TestitApiClient.GetShortProjectsApiModel);
    });

    it('should have the property inquiry (base name: "inquiry")', function() {
      // uncomment below and update the code to test the property inquiry
      //var instance = new TestitApiClient.GetShortProjectsApiModel();
      //expect(instance).to.be();
    });

    it('should have the property permissionName (base name: "permissionName")', function() {
      // uncomment below and update the code to test the property permissionName
      //var instance = new TestitApiClient.GetShortProjectsApiModel();
      //expect(instance).to.be();
    });

    it('should have the property permissionType (base name: "permissionType")', function() {
      // uncomment below and update the code to test the property permissionType
      //var instance = new TestitApiClient.GetShortProjectsApiModel();
      //expect(instance).to.be();
    });

  });

}));
