/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.testit_api_client);
  }
}(this, function(expect, testit_api_client) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new testit_api_client.WorkItemFilterModel();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('WorkItemFilterModel', function() {
    it('should create an instance of WorkItemFilterModel', function() {
      // uncomment below and update the code to test WorkItemFilterModel
      //var instance = new testit_api_client.WorkItemFilterModel();
      //expect(instance).to.be.a(testit_api_client.WorkItemFilterModel);
    });

    it('should have the property nameOrId (base name: "nameOrId")', function() {
      // uncomment below and update the code to test the property nameOrId
      //var instance = new testit_api_client.WorkItemFilterModel();
      //expect(instance).to.be();
    });

    it('should have the property includeIds (base name: "includeIds")', function() {
      // uncomment below and update the code to test the property includeIds
      //var instance = new testit_api_client.WorkItemFilterModel();
      //expect(instance).to.be();
    });

    it('should have the property excludeIds (base name: "excludeIds")', function() {
      // uncomment below and update the code to test the property excludeIds
      //var instance = new testit_api_client.WorkItemFilterModel();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new testit_api_client.WorkItemFilterModel();
      //expect(instance).to.be();
    });

    it('should have the property globalIds (base name: "globalIds")', function() {
      // uncomment below and update the code to test the property globalIds
      //var instance = new testit_api_client.WorkItemFilterModel();
      //expect(instance).to.be();
    });

    it('should have the property attributes (base name: "attributes")', function() {
      // uncomment below and update the code to test the property attributes
      //var instance = new testit_api_client.WorkItemFilterModel();
      //expect(instance).to.be();
    });

    it('should have the property isDeleted (base name: "isDeleted")', function() {
      // uncomment below and update the code to test the property isDeleted
      //var instance = new testit_api_client.WorkItemFilterModel();
      //expect(instance).to.be();
    });

    it('should have the property projectIds (base name: "projectIds")', function() {
      // uncomment below and update the code to test the property projectIds
      //var instance = new testit_api_client.WorkItemFilterModel();
      //expect(instance).to.be();
    });

    it('should have the property sectionIds (base name: "sectionIds")', function() {
      // uncomment below and update the code to test the property sectionIds
      //var instance = new testit_api_client.WorkItemFilterModel();
      //expect(instance).to.be();
    });

    it('should have the property createdByIds (base name: "createdByIds")', function() {
      // uncomment below and update the code to test the property createdByIds
      //var instance = new testit_api_client.WorkItemFilterModel();
      //expect(instance).to.be();
    });

    it('should have the property modifiedByIds (base name: "modifiedByIds")', function() {
      // uncomment below and update the code to test the property modifiedByIds
      //var instance = new testit_api_client.WorkItemFilterModel();
      //expect(instance).to.be();
    });

    it('should have the property states (base name: "states")', function() {
      // uncomment below and update the code to test the property states
      //var instance = new testit_api_client.WorkItemFilterModel();
      //expect(instance).to.be();
    });

    it('should have the property priorities (base name: "priorities")', function() {
      // uncomment below and update the code to test the property priorities
      //var instance = new testit_api_client.WorkItemFilterModel();
      //expect(instance).to.be();
    });

    it('should have the property entityTypes (base name: "entityTypes")', function() {
      // uncomment below and update the code to test the property entityTypes
      //var instance = new testit_api_client.WorkItemFilterModel();
      //expect(instance).to.be();
    });

    it('should have the property createdDateMinimal (base name: "createdDateMinimal")', function() {
      // uncomment below and update the code to test the property createdDateMinimal
      //var instance = new testit_api_client.WorkItemFilterModel();
      //expect(instance).to.be();
    });

    it('should have the property createdDateMaximal (base name: "createdDateMaximal")', function() {
      // uncomment below and update the code to test the property createdDateMaximal
      //var instance = new testit_api_client.WorkItemFilterModel();
      //expect(instance).to.be();
    });

    it('should have the property modifiedDateMinimal (base name: "modifiedDateMinimal")', function() {
      // uncomment below and update the code to test the property modifiedDateMinimal
      //var instance = new testit_api_client.WorkItemFilterModel();
      //expect(instance).to.be();
    });

    it('should have the property modifiedDateMaximal (base name: "modifiedDateMaximal")', function() {
      // uncomment below and update the code to test the property modifiedDateMaximal
      //var instance = new testit_api_client.WorkItemFilterModel();
      //expect(instance).to.be();
    });

    it('should have the property durationMinimal (base name: "durationMinimal")', function() {
      // uncomment below and update the code to test the property durationMinimal
      //var instance = new testit_api_client.WorkItemFilterModel();
      //expect(instance).to.be();
    });

    it('should have the property durationMaximal (base name: "durationMaximal")', function() {
      // uncomment below and update the code to test the property durationMaximal
      //var instance = new testit_api_client.WorkItemFilterModel();
      //expect(instance).to.be();
    });

    it('should have the property isAutomated (base name: "isAutomated")', function() {
      // uncomment below and update the code to test the property isAutomated
      //var instance = new testit_api_client.WorkItemFilterModel();
      //expect(instance).to.be();
    });

    it('should have the property tagNames (base name: "tagNames")', function() {
      // uncomment below and update the code to test the property tagNames
      //var instance = new testit_api_client.WorkItemFilterModel();
      //expect(instance).to.be();
    });

    it('should have the property autoTestIds (base name: "autoTestIds")', function() {
      // uncomment below and update the code to test the property autoTestIds
      //var instance = new testit_api_client.WorkItemFilterModel();
      //expect(instance).to.be();
    });

    it('should have the property exceptWorkItemIds (base name: "exceptWorkItemIds")', function() {
      // uncomment below and update the code to test the property exceptWorkItemIds
      //var instance = new testit_api_client.WorkItemFilterModel();
      //expect(instance).to.be();
    });

  });

}));
